# docker-compose.yml
version: '3.8'

services:
  sveltekit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "4173:4173"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
